### ISSUE TITLE
Statamic 2.6.7 Upgrade Incompatible?

### ISSUE THREAD

**Issue by intrepidws** [TheLifeProject/bugsnag-for-statamic#1]
When upgrading to Statamic 2.6.7 I got a composer update error. When I remove this addon, the error went away. The error was:
```
  [Symfony\Component\Process\Exception\ProcessFailedException]
  The command "php composer.phar update the-life-project/bugsnag-logger --prefer-dist --no-dev --optimize-autoloader" failed.
  Exit Code: 2(Misuse of shell builtins)
  Output:
  ================
  Error Output:
  ================
  Loading composer repositories with package information
  Updating dependencies
  Your requirements could not be resolved to an installable set of packages.
    Problem 1
      - The requested package michelf/php-markdown (locked at 1.7.0, required as 1.6.0) is satisfiable by michelf/php-markdown[1.7.0
  ] but these conflict with your requirements or minimum-stability.
```

**Comment by sheldonkotyk** [comment]
OK, we'll take look.

**Comment by intrepidws** [comment]
Have you had a chance to look into this?

**Comment by warkior** [comment]
This is a strange one. Our code doesn't rely at all on michelf/php-markdown. That's a dependency of Statamic. Ours only has `"bugsnag/bugsnag": "^3.0"` as a dependency as you should be able to see in the composer.json file. I've looked through the bugsnag dependencies too, and don't see any reference to michelf/php-markdown.

Is there possibly some other addon you might be using that depends on a specific version of php-markdown?

**Comment by intrepidws** [comment]
Well, I just upgraded to Statamic 2.8.7 and tried installing the package again - and it works fine now.

No idea whether there was some problem specific to Statamic 2.6.7, but it works now.

Thanks for the package, works great.
